#![allow(clippy::too_many_lines, clippy::match_same_arms)]

use core::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum Domain {
    Hub,
    Transfer,
    Artifact,
    Engine,
    Accel,
    Resource,
    Record,
    Config,
    Probe,
    Lab,
    Model,
    Sandbox,
    Platform,
    Time,
    Exchange,
    Internal,
}

impl Domain {
    pub const ALL: [Self; 16] = [
        Self::Hub,
        Self::Transfer,
        Self::Artifact,
        Self::Engine,
        Self::Accel,
        Self::Resource,
        Self::Record,
        Self::Config,
        Self::Probe,
        Self::Lab,
        Self::Model,
        Self::Sandbox,
        Self::Platform,
        Self::Time,
        Self::Exchange,
        Self::Internal,
    ];

    #[must_use]
    pub const fn prefix(self) -> &'static str {
        match self {
            Self::Hub => "hub",
            Self::Transfer => "transfer",
            Self::Artifact => "artifact",
            Self::Engine => "engine",
            Self::Accel => "accel",
            Self::Resource => "resource",
            Self::Record => "record",
            Self::Config => "config",
            Self::Probe => "probe",
            Self::Lab => "lab",
            Self::Model => "model",
            Self::Sandbox => "sandbox",
            Self::Platform => "platform",
            Self::Time => "time",
            Self::Exchange => "exchange",
            Self::Internal => "internal",
        }
    }

    #[must_use]
    pub const fn subject(self) -> &'static str {
        match self {
            Self::Hub => "the model source",
            Self::Transfer => "getting bytes here",
            Self::Artifact => "a local model artifact",
            Self::Engine => "the supervised inference process",
            Self::Accel => "the accelerator",
            Self::Resource => "the machine's own limits",
            Self::Record => "the record store",
            Self::Config => "configuration",
            Self::Probe => "capability probing",
            Self::Lab => "laboratory execution",
            Self::Model => "the model under test's behaviour",
            Self::Sandbox => "containment",
            Self::Platform => "the operating system and privilege",
            Self::Time => "the clock",
            Self::Exchange => "identifiers and contributions",
            Self::Internal => "MCF's own invariants",
        }
    }
}

impl fmt::Display for Domain {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.prefix())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum Category {
    HubUnreachable,
    HubRateLimited,
    HubAuthRequired,
    HubAuthRejected,
    HubAccessGated,
    HubRefNotFound,
    HubRefMoved,
    HubMetadataAbsent,
    HubMetadataMalformed,
    HubMetadataDeceptive,
    HubLicenceUnparseable,
    HubLicenceForbidsUse,
    TransferStalled,
    TransferTruncated,
    TransferMutated,
    TransferChecksumMismatch,
    TransferInterrupted,
    TransferTls,
    ArtifactMissing,
    ArtifactCorrupt,
    ArtifactUnreadable,
    ArtifactFormatUnsupported,
    ArtifactFormatMalformed,
    ArtifactIncomplete,
    ArtifactArchiveTraversal,
    ArtifactArchiveOversized,
    ArtifactProvenanceIncomplete,
    EngineSpawnNotFound,
    EngineSpawnRefused,
    EngineExitImmediate,
    EngineExitMidstream,
    EngineExitSignal,
    EngineHangNoOutput,
    EngineProtocolMalformed,
    EngineProtocolVersion,
    EngineLoadRefused,
    EngineUnavailable,
    AccelAbsent,
    AccelUnrecognized,
    AccelDriverAbsent,
    AccelDriverQueryFailed,
    AccelDriverVersionMismatch,
    AccelMemoryExhausted,
    AccelMemoryFragmented,
    AccelThermalCeiling,
    AccelReset,
    AccelLost,
    ResourceDiskExhausted,
    ResourceDiskReadonly,
    ResourceDiskQuota,
    ResourceMemoryExhausted,
    ResourceMemoryPressure,
    ResourceFdExhausted,
    ResourceContended,
    RecordUnwritable,
    RecordCorruptIndex,
    RecordCorruptJournal,
    RecordReplayIncomplete,
    RecordSchemaUnknown,
    RecordBudgetExhausted,
    RecordContentUnreadable,
    ConfigInvalid,
    ConfigUnsatisfiable,
    ConfigConflict,
    ConfigUnverified,
    ConfigIdentityMismatch,
    ProbeInconclusive,
    ProbeTimeout,
    ProbeMalformedResponse,
    ProbeUnsupported,
    ProbeDivergence,
    LabSetupFailed,
    LabTeardownFailed,
    LabGateNotApplicable,
    LabGateUnknown,
    LabPreconditionContended,
    LabBudgetExceeded,
    LabInterrupted,
    LabWorkloadUngradable,
    LabConditionsInvalidated,
    ModelToolMalformedCall,
    ModelToolWrongSelection,
    ModelToolHallucinated,
    ModelLoopNoProgress,
    ModelStopNever,
    ModelStopPremature,
    ModelRecoveryNone,
    ModelFormatViolated,
    ModelInstructionIgnored,
    ModelRefused,
    ModelOutputEmpty,
    SandboxEscapeAttempted,
    SandboxQuotaDisk,
    SandboxQuotaMemory,
    SandboxTurnBudget,
    SandboxConstructFailed,
    PlatformUnsupported,
    PlatformPrivilegeDenied,
    PlatformPrivilegeUnavailable,
    PlatformMechanismUnavailable,
    PlatformRestoreFailed,
    TimeJumpBackward,
    TimeJumpForward,
    TimeMonotonicUnavailable,
    ExchangeIdentifierMalformed,
    ExchangeIdentifierUnresolvable,
    ExchangeReproduceImpossible,
    ExchangeReproduceDivergent,
    ExchangeSchemaUnreadable,
    ExchangeTermsAbsent,
    InternalInvariantViolated,
    InternalUnclassified,
}

impl Category {
    pub const ALL: [Self; 112] = [
        Self::HubUnreachable,
        Self::HubRateLimited,
        Self::HubAuthRequired,
        Self::HubAuthRejected,
        Self::HubAccessGated,
        Self::HubRefNotFound,
        Self::HubRefMoved,
        Self::HubMetadataAbsent,
        Self::HubMetadataMalformed,
        Self::HubMetadataDeceptive,
        Self::HubLicenceUnparseable,
        Self::HubLicenceForbidsUse,
        Self::TransferStalled,
        Self::TransferTruncated,
        Self::TransferMutated,
        Self::TransferChecksumMismatch,
        Self::TransferInterrupted,
        Self::TransferTls,
        Self::ArtifactMissing,
        Self::ArtifactCorrupt,
        Self::ArtifactUnreadable,
        Self::ArtifactFormatUnsupported,
        Self::ArtifactFormatMalformed,
        Self::ArtifactIncomplete,
        Self::ArtifactArchiveTraversal,
        Self::ArtifactArchiveOversized,
        Self::ArtifactProvenanceIncomplete,
        Self::EngineSpawnNotFound,
        Self::EngineSpawnRefused,
        Self::EngineExitImmediate,
        Self::EngineExitMidstream,
        Self::EngineExitSignal,
        Self::EngineHangNoOutput,
        Self::EngineProtocolMalformed,
        Self::EngineProtocolVersion,
        Self::EngineLoadRefused,
        Self::EngineUnavailable,
        Self::AccelAbsent,
        Self::AccelUnrecognized,
        Self::AccelDriverAbsent,
        Self::AccelDriverQueryFailed,
        Self::AccelDriverVersionMismatch,
        Self::AccelMemoryExhausted,
        Self::AccelMemoryFragmented,
        Self::AccelThermalCeiling,
        Self::AccelReset,
        Self::AccelLost,
        Self::ResourceDiskExhausted,
        Self::ResourceDiskReadonly,
        Self::ResourceDiskQuota,
        Self::ResourceMemoryExhausted,
        Self::ResourceMemoryPressure,
        Self::ResourceFdExhausted,
        Self::ResourceContended,
        Self::RecordUnwritable,
        Self::RecordCorruptIndex,
        Self::RecordCorruptJournal,
        Self::RecordReplayIncomplete,
        Self::RecordSchemaUnknown,
        Self::RecordBudgetExhausted,
        Self::RecordContentUnreadable,
        Self::ConfigInvalid,
        Self::ConfigUnsatisfiable,
        Self::ConfigConflict,
        Self::ConfigUnverified,
        Self::ConfigIdentityMismatch,
        Self::ProbeInconclusive,
        Self::ProbeTimeout,
        Self::ProbeMalformedResponse,
        Self::ProbeUnsupported,
        Self::ProbeDivergence,
        Self::LabSetupFailed,
        Self::LabTeardownFailed,
        Self::LabGateNotApplicable,
        Self::LabGateUnknown,
        Self::LabPreconditionContended,
        Self::LabBudgetExceeded,
        Self::LabInterrupted,
        Self::LabWorkloadUngradable,
        Self::LabConditionsInvalidated,
        Self::ModelToolMalformedCall,
        Self::ModelToolWrongSelection,
        Self::ModelToolHallucinated,
        Self::ModelLoopNoProgress,
        Self::ModelStopNever,
        Self::ModelStopPremature,
        Self::ModelRecoveryNone,
        Self::ModelFormatViolated,
        Self::ModelInstructionIgnored,
        Self::ModelRefused,
        Self::ModelOutputEmpty,
        Self::SandboxEscapeAttempted,
        Self::SandboxQuotaDisk,
        Self::SandboxQuotaMemory,
        Self::SandboxTurnBudget,
        Self::SandboxConstructFailed,
        Self::PlatformUnsupported,
        Self::PlatformPrivilegeDenied,
        Self::PlatformPrivilegeUnavailable,
        Self::PlatformMechanismUnavailable,
        Self::PlatformRestoreFailed,
        Self::TimeJumpBackward,
        Self::TimeJumpForward,
        Self::TimeMonotonicUnavailable,
        Self::ExchangeIdentifierMalformed,
        Self::ExchangeIdentifierUnresolvable,
        Self::ExchangeReproduceImpossible,
        Self::ExchangeReproduceDivergent,
        Self::ExchangeSchemaUnreadable,
        Self::ExchangeTermsAbsent,
        Self::InternalInvariantViolated,
        Self::InternalUnclassified,
    ];

    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::HubUnreachable => "hub.unreachable",
            Self::HubRateLimited => "hub.rate_limited",
            Self::HubAuthRequired => "hub.auth.required",
            Self::HubAuthRejected => "hub.auth.rejected",
            Self::HubAccessGated => "hub.access.gated",
            Self::HubRefNotFound => "hub.ref.not_found",
            Self::HubRefMoved => "hub.ref.moved",
            Self::HubMetadataAbsent => "hub.metadata.absent",
            Self::HubMetadataMalformed => "hub.metadata.malformed",
            Self::HubMetadataDeceptive => "hub.metadata.deceptive",
            Self::HubLicenceUnparseable => "hub.licence.unparseable",
            Self::HubLicenceForbidsUse => "hub.licence.forbids_use",
            Self::TransferStalled => "transfer.stalled",
            Self::TransferTruncated => "transfer.truncated",
            Self::TransferMutated => "transfer.mutated",
            Self::TransferChecksumMismatch => "transfer.checksum_mismatch",
            Self::TransferInterrupted => "transfer.interrupted",
            Self::TransferTls => "transfer.tls",
            Self::ArtifactMissing => "artifact.missing",
            Self::ArtifactCorrupt => "artifact.corrupt",
            Self::ArtifactUnreadable => "artifact.unreadable",
            Self::ArtifactFormatUnsupported => "artifact.format.unsupported",
            Self::ArtifactFormatMalformed => "artifact.format.malformed",
            Self::ArtifactIncomplete => "artifact.incomplete",
            Self::ArtifactArchiveTraversal => "artifact.archive.traversal",
            Self::ArtifactArchiveOversized => "artifact.archive.oversized",
            Self::ArtifactProvenanceIncomplete => "artifact.provenance.incomplete",
            Self::EngineSpawnNotFound => "engine.spawn.not_found",
            Self::EngineSpawnRefused => "engine.spawn.refused",
            Self::EngineExitImmediate => "engine.exit.immediate",
            Self::EngineExitMidstream => "engine.exit.midstream",
            Self::EngineExitSignal => "engine.exit.signal",
            Self::EngineHangNoOutput => "engine.hang.no_output",
            Self::EngineProtocolMalformed => "engine.protocol.malformed",
            Self::EngineProtocolVersion => "engine.protocol.version",
            Self::EngineLoadRefused => "engine.load.refused",
            Self::EngineUnavailable => "engine.unavailable",
            Self::AccelAbsent => "accel.absent",
            Self::AccelUnrecognized => "accel.unrecognized",
            Self::AccelDriverAbsent => "accel.driver.absent",
            Self::AccelDriverQueryFailed => "accel.driver.query_failed",
            Self::AccelDriverVersionMismatch => "accel.driver.version_mismatch",
            Self::AccelMemoryExhausted => "accel.memory.exhausted",
            Self::AccelMemoryFragmented => "accel.memory.fragmented",
            Self::AccelThermalCeiling => "accel.thermal.ceiling",
            Self::AccelReset => "accel.reset",
            Self::AccelLost => "accel.lost",
            Self::ResourceDiskExhausted => "resource.disk.exhausted",
            Self::ResourceDiskReadonly => "resource.disk.readonly",
            Self::ResourceDiskQuota => "resource.disk.quota",
            Self::ResourceMemoryExhausted => "resource.memory.exhausted",
            Self::ResourceMemoryPressure => "resource.memory.pressure",
            Self::ResourceFdExhausted => "resource.fd.exhausted",
            Self::ResourceContended => "resource.contended",
            Self::RecordUnwritable => "record.unwritable",
            Self::RecordCorruptIndex => "record.corrupt.index",
            Self::RecordCorruptJournal => "record.corrupt.journal",
            Self::RecordReplayIncomplete => "record.replay.incomplete",
            Self::RecordSchemaUnknown => "record.schema.unknown",
            Self::RecordBudgetExhausted => "record.budget.exhausted",
            Self::RecordContentUnreadable => "record.content.unreadable",
            Self::ConfigInvalid => "config.invalid",
            Self::ConfigUnsatisfiable => "config.unsatisfiable",
            Self::ConfigConflict => "config.conflict",
            Self::ConfigUnverified => "config.unverified",
            Self::ConfigIdentityMismatch => "config.identity.mismatch",
            Self::ProbeInconclusive => "probe.inconclusive",
            Self::ProbeTimeout => "probe.timeout",
            Self::ProbeMalformedResponse => "probe.malformed_response",
            Self::ProbeUnsupported => "probe.unsupported",
            Self::ProbeDivergence => "probe.divergence",
            Self::LabSetupFailed => "lab.setup.failed",
            Self::LabTeardownFailed => "lab.teardown.failed",
            Self::LabGateNotApplicable => "lab.gate.not_applicable",
            Self::LabGateUnknown => "lab.gate.unknown",
            Self::LabPreconditionContended => "lab.precondition.contended",
            Self::LabBudgetExceeded => "lab.budget.exceeded",
            Self::LabInterrupted => "lab.interrupted",
            Self::LabWorkloadUngradable => "lab.workload.ungradable",
            Self::LabConditionsInvalidated => "lab.conditions.invalidated",
            Self::ModelToolMalformedCall => "model.tool.malformed_call",
            Self::ModelToolWrongSelection => "model.tool.wrong_selection",
            Self::ModelToolHallucinated => "model.tool.hallucinated",
            Self::ModelLoopNoProgress => "model.loop.no_progress",
            Self::ModelStopNever => "model.stop.never",
            Self::ModelStopPremature => "model.stop.premature",
            Self::ModelRecoveryNone => "model.recovery.none",
            Self::ModelFormatViolated => "model.format.violated",
            Self::ModelInstructionIgnored => "model.instruction.ignored",
            Self::ModelRefused => "model.refused",
            Self::ModelOutputEmpty => "model.output.empty",
            Self::SandboxEscapeAttempted => "sandbox.escape_attempted",
            Self::SandboxQuotaDisk => "sandbox.quota.disk",
            Self::SandboxQuotaMemory => "sandbox.quota.memory",
            Self::SandboxTurnBudget => "sandbox.turn_budget",
            Self::SandboxConstructFailed => "sandbox.construct_failed",
            Self::PlatformUnsupported => "platform.unsupported",
            Self::PlatformPrivilegeDenied => "platform.privilege.denied",
            Self::PlatformPrivilegeUnavailable => "platform.privilege.unavailable",
            Self::PlatformMechanismUnavailable => "platform.mechanism.unavailable",
            Self::PlatformRestoreFailed => "platform.restore_failed",
            Self::TimeJumpBackward => "time.jump.backward",
            Self::TimeJumpForward => "time.jump.forward",
            Self::TimeMonotonicUnavailable => "time.monotonic.unavailable",
            Self::ExchangeIdentifierMalformed => "exchange.identifier.malformed",
            Self::ExchangeIdentifierUnresolvable => "exchange.identifier.unresolvable",
            Self::ExchangeReproduceImpossible => "exchange.reproduce.impossible",
            Self::ExchangeReproduceDivergent => "exchange.reproduce.divergent",
            Self::ExchangeSchemaUnreadable => "exchange.schema.unreadable",
            Self::ExchangeTermsAbsent => "exchange.terms.absent",
            Self::InternalInvariantViolated => "internal.invariant_violated",
            Self::InternalUnclassified => "internal.unclassified",
        }
    }

    #[must_use]
    pub const fn meaning(self) -> &'static str {
        match self {
            Self::HubUnreachable => "No route to the hub",
            Self::HubRateLimited => "Throttled, with or without a retry hint",
            Self::HubAuthRequired => "Credentials absent",
            Self::HubAuthRejected => "Credentials present and refused",
            Self::HubAccessGated => "Terms not accepted for this account",
            Self::HubRefNotFound => "Repository or revision does not exist",
            Self::HubRefMoved => "Tag repointed between resolve and fetch",
            Self::HubMetadataAbsent => "No config, card or licence",
            Self::HubMetadataMalformed => "Present and unparseable",
            Self::HubMetadataDeceptive => "Declares an architecture the weights are not",
            Self::HubLicenceUnparseable => "Licence text present, terms unmatchable",
            Self::HubLicenceForbidsUse => "Terms forbid the attempted use",
            Self::TransferStalled => "No progress past the deadline",
            Self::TransferTruncated => "Stream ended before the declared length",
            Self::TransferMutated => "Content changed between manifest and fetch",
            Self::TransferChecksumMismatch => "Bytes arrived and do not verify",
            Self::TransferInterrupted => "Connection lost; resumable",
            Self::TransferTls => "Certificate or handshake failure",
            Self::ArtifactMissing => "Referenced and not present",
            Self::ArtifactCorrupt => "Present and fails verification on re-check",
            Self::ArtifactUnreadable => "Present and cannot be read at all",
            Self::ArtifactFormatUnsupported => "A format MCF does not read",
            Self::ArtifactFormatMalformed => "A format MCF reads, malformed",
            Self::ArtifactIncomplete => "Some shards present, others absent",
            Self::ArtifactArchiveTraversal => "Member escapes the extraction root",
            Self::ArtifactArchiveOversized => "Expands beyond its declared size",
            Self::ArtifactProvenanceIncomplete => "Held, with unknown fields",
            Self::EngineSpawnNotFound => "Binary absent at spawn",
            Self::EngineSpawnRefused => "Permission or platform refusal",
            Self::EngineExitImmediate => "Died before first output",
            Self::EngineExitMidstream => "Died after partial output",
            Self::EngineExitSignal => "Killed by signal, including the OOM killer",
            Self::EngineHangNoOutput => "Alive, silent, past deadline",
            Self::EngineProtocolMalformed => "Output MCF cannot parse",
            Self::EngineProtocolVersion => "Incompatible engine interface",
            Self::EngineLoadRefused => "Engine declines the model",
            Self::EngineUnavailable => "No vendored engine supports this artifact",
            Self::AccelAbsent => "None present",
            Self::AccelUnrecognized => "Present, not characterized",
            Self::AccelDriverAbsent => "No driver",
            Self::AccelDriverQueryFailed => "Driver present, interrogation failed",
            Self::AccelDriverVersionMismatch => "Runtime and driver disagree",
            Self::AccelMemoryExhausted => "Allocation refused",
            Self::AccelMemoryFragmented => "Free but unallocatable",
            Self::AccelThermalCeiling => "Sustained throttle",
            Self::AccelReset => "Device reset mid-operation",
            Self::AccelLost => "Disappeared from the bus",
            Self::ResourceDiskExhausted => "No space, operation in flight",
            Self::ResourceDiskReadonly => "Volume remounted read-only",
            Self::ResourceDiskQuota => "Quota refused the write",
            Self::ResourceMemoryExhausted => "Host allocation refused",
            Self::ResourceMemoryPressure => "Allocatable but degraded",
            Self::ResourceFdExhausted => "Descriptor limit",
            Self::ResourceContended => "Another process holds what was needed",
            Self::RecordUnwritable => "Store cannot be opened for writing",
            Self::RecordCorruptIndex => "Derived database damaged; journal intact",
            Self::RecordCorruptJournal => "Journal damaged",
            Self::RecordReplayIncomplete => "Rebuilt, with a stated gap",
            Self::RecordSchemaUnknown => "Written by a version this one cannot read",
            Self::RecordBudgetExhausted => "Retention limit reached",
            Self::RecordContentUnreadable => {
                "Content filed beside the record is there and will not be read"
            }
            Self::ConfigInvalid => "Value outside the permitted domain",
            Self::ConfigUnsatisfiable => "Coherent and impossible on this machine",
            Self::ConfigConflict => "Two settings that cannot both hold",
            Self::ConfigUnverified => "Declared, never probed, and required to be",
            Self::ConfigIdentityMismatch => "Realized differs from declared (placement)",
            Self::ProbeInconclusive => "Neither confirms nor denies",
            Self::ProbeTimeout => "No result within its bound",
            Self::ProbeMalformedResponse => "Output the probe cannot grade",
            Self::ProbeUnsupported => "Probe does not apply to this artifact",
            Self::ProbeDivergence => "Declared and verified disagree — a *finding*, not an error",
            Self::LabSetupFailed => "Environment could not be constructed",
            Self::LabTeardownFailed => "Residue left behind",
            Self::LabGateNotApplicable => "Capability verified absent — not a failure",
            Self::LabGateUnknown => "Capability unestablished (B40)",
            Self::LabPreconditionContended => "Machine not quiet for a timing run",
            Self::LabBudgetExceeded => "Declared maximum duration reached",
            Self::LabInterrupted => "Stopped by the operator; partial preserved",
            Self::LabWorkloadUngradable => "Supplied workload cannot be graded",
            Self::LabConditionsInvalidated => "Conditions moved mid-run; result unsound",
            Self::ModelToolMalformedCall => "Unparseable or missing required arguments",
            Self::ModelToolWrongSelection => "Plausible but incorrect tool",
            Self::ModelToolHallucinated => "Tool that does not exist",
            Self::ModelLoopNoProgress => "Repeats an action with unchanged state",
            Self::ModelStopNever => "Runs to the turn or token budget",
            Self::ModelStopPremature => "Stops with the task incomplete",
            Self::ModelRecoveryNone => "Receives an error and repeats unchanged",
            Self::ModelFormatViolated => "Correct content, wrong required format",
            Self::ModelInstructionIgnored => "A stated constraint unmet",
            Self::ModelRefused => "Declined the task",
            Self::ModelOutputEmpty => "Produced nothing",
            Self::SandboxEscapeAttempted => {
                "Reached for something absent — recorded, never permitted"
            }
            Self::SandboxQuotaDisk => "Environment quota refused a write",
            Self::SandboxQuotaMemory => "Environment limit reached",
            Self::SandboxTurnBudget => "Turn limit reached",
            Self::SandboxConstructFailed => "Environment could not be built",
            Self::PlatformUnsupported => "Outside the declared scope",
            Self::PlatformPrivilegeDenied => "Elevation refused (A26)",
            Self::PlatformPrivilegeUnavailable => "No mechanism on this platform",
            Self::PlatformMechanismUnavailable => "Boxing, pinning or yielding unsupported here",
            Self::PlatformRestoreFailed => "Something changed could not be restored",
            Self::TimeJumpBackward => "Wall clock stepped back mid-measurement",
            Self::TimeJumpForward => "Large forward step",
            Self::TimeMonotonicUnavailable => "No monotonic source",
            Self::ExchangeIdentifierMalformed => "Unparseable",
            Self::ExchangeIdentifierUnresolvable => "Names something unobtainable",
            Self::ExchangeReproduceImpossible => {
                "Resolvable and cannot run here — a complete answer"
            }
            Self::ExchangeReproduceDivergent => "Reproduced; numbers differ — a *finding*",
            Self::ExchangeSchemaUnreadable => "Contribution written by an uninterpretable version",
            Self::ExchangeTermsAbsent => "Terms not shown before sending — a defect",
            Self::InternalInvariantViolated => "A state the type system was meant to prevent",
            Self::InternalUnclassified => "A failure that fits nothing above",
        }
    }

    #[must_use]
    pub const fn domain(self) -> Domain {
        match self {
            Self::HubUnreachable => Domain::Hub,
            Self::HubRateLimited => Domain::Hub,
            Self::HubAuthRequired => Domain::Hub,
            Self::HubAuthRejected => Domain::Hub,
            Self::HubAccessGated => Domain::Hub,
            Self::HubRefNotFound => Domain::Hub,
            Self::HubRefMoved => Domain::Hub,
            Self::HubMetadataAbsent => Domain::Hub,
            Self::HubMetadataMalformed => Domain::Hub,
            Self::HubMetadataDeceptive => Domain::Hub,
            Self::HubLicenceUnparseable => Domain::Hub,
            Self::HubLicenceForbidsUse => Domain::Hub,
            Self::TransferStalled => Domain::Transfer,
            Self::TransferTruncated => Domain::Transfer,
            Self::TransferMutated => Domain::Transfer,
            Self::TransferChecksumMismatch => Domain::Transfer,
            Self::TransferInterrupted => Domain::Transfer,
            Self::TransferTls => Domain::Transfer,
            Self::ArtifactMissing => Domain::Artifact,
            Self::ArtifactCorrupt => Domain::Artifact,
            Self::ArtifactUnreadable => Domain::Artifact,
            Self::ArtifactFormatUnsupported => Domain::Artifact,
            Self::ArtifactFormatMalformed => Domain::Artifact,
            Self::ArtifactIncomplete => Domain::Artifact,
            Self::ArtifactArchiveTraversal => Domain::Artifact,
            Self::ArtifactArchiveOversized => Domain::Artifact,
            Self::ArtifactProvenanceIncomplete => Domain::Artifact,
            Self::EngineSpawnNotFound => Domain::Engine,
            Self::EngineSpawnRefused => Domain::Engine,
            Self::EngineExitImmediate => Domain::Engine,
            Self::EngineExitMidstream => Domain::Engine,
            Self::EngineExitSignal => Domain::Engine,
            Self::EngineHangNoOutput => Domain::Engine,
            Self::EngineProtocolMalformed => Domain::Engine,
            Self::EngineProtocolVersion => Domain::Engine,
            Self::EngineLoadRefused => Domain::Engine,
            Self::EngineUnavailable => Domain::Engine,
            Self::AccelAbsent => Domain::Accel,
            Self::AccelUnrecognized => Domain::Accel,
            Self::AccelDriverAbsent => Domain::Accel,
            Self::AccelDriverQueryFailed => Domain::Accel,
            Self::AccelDriverVersionMismatch => Domain::Accel,
            Self::AccelMemoryExhausted => Domain::Accel,
            Self::AccelMemoryFragmented => Domain::Accel,
            Self::AccelThermalCeiling => Domain::Accel,
            Self::AccelReset => Domain::Accel,
            Self::AccelLost => Domain::Accel,
            Self::ResourceDiskExhausted => Domain::Resource,
            Self::ResourceDiskReadonly => Domain::Resource,
            Self::ResourceDiskQuota => Domain::Resource,
            Self::ResourceMemoryExhausted => Domain::Resource,
            Self::ResourceMemoryPressure => Domain::Resource,
            Self::ResourceFdExhausted => Domain::Resource,
            Self::ResourceContended => Domain::Resource,
            Self::RecordUnwritable => Domain::Record,
            Self::RecordCorruptIndex => Domain::Record,
            Self::RecordCorruptJournal => Domain::Record,
            Self::RecordReplayIncomplete => Domain::Record,
            Self::RecordSchemaUnknown => Domain::Record,
            Self::RecordBudgetExhausted | Self::RecordContentUnreadable => Domain::Record,
            Self::ConfigInvalid => Domain::Config,
            Self::ConfigUnsatisfiable => Domain::Config,
            Self::ConfigConflict => Domain::Config,
            Self::ConfigUnverified => Domain::Config,
            Self::ConfigIdentityMismatch => Domain::Config,
            Self::ProbeInconclusive => Domain::Probe,
            Self::ProbeTimeout => Domain::Probe,
            Self::ProbeMalformedResponse => Domain::Probe,
            Self::ProbeUnsupported => Domain::Probe,
            Self::ProbeDivergence => Domain::Probe,
            Self::LabSetupFailed => Domain::Lab,
            Self::LabTeardownFailed => Domain::Lab,
            Self::LabGateNotApplicable => Domain::Lab,
            Self::LabGateUnknown => Domain::Lab,
            Self::LabPreconditionContended => Domain::Lab,
            Self::LabBudgetExceeded => Domain::Lab,
            Self::LabInterrupted => Domain::Lab,
            Self::LabWorkloadUngradable => Domain::Lab,
            Self::LabConditionsInvalidated => Domain::Lab,
            Self::ModelToolMalformedCall => Domain::Model,
            Self::ModelToolWrongSelection => Domain::Model,
            Self::ModelToolHallucinated => Domain::Model,
            Self::ModelLoopNoProgress => Domain::Model,
            Self::ModelStopNever => Domain::Model,
            Self::ModelStopPremature => Domain::Model,
            Self::ModelRecoveryNone => Domain::Model,
            Self::ModelFormatViolated => Domain::Model,
            Self::ModelInstructionIgnored => Domain::Model,
            Self::ModelRefused => Domain::Model,
            Self::ModelOutputEmpty => Domain::Model,
            Self::SandboxEscapeAttempted => Domain::Sandbox,
            Self::SandboxQuotaDisk => Domain::Sandbox,
            Self::SandboxQuotaMemory => Domain::Sandbox,
            Self::SandboxTurnBudget => Domain::Sandbox,
            Self::SandboxConstructFailed => Domain::Sandbox,
            Self::PlatformUnsupported => Domain::Platform,
            Self::PlatformPrivilegeDenied => Domain::Platform,
            Self::PlatformPrivilegeUnavailable => Domain::Platform,
            Self::PlatformMechanismUnavailable => Domain::Platform,
            Self::PlatformRestoreFailed => Domain::Platform,
            Self::TimeJumpBackward => Domain::Time,
            Self::TimeJumpForward => Domain::Time,
            Self::TimeMonotonicUnavailable => Domain::Time,
            Self::ExchangeIdentifierMalformed => Domain::Exchange,
            Self::ExchangeIdentifierUnresolvable => Domain::Exchange,
            Self::ExchangeReproduceImpossible => Domain::Exchange,
            Self::ExchangeReproduceDivergent => Domain::Exchange,
            Self::ExchangeSchemaUnreadable => Domain::Exchange,
            Self::ExchangeTermsAbsent => Domain::Exchange,
            Self::InternalInvariantViolated => Domain::Internal,
            Self::InternalUnclassified => Domain::Internal,
        }
    }

    #[must_use]
    pub fn from_code(code: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|category| category.code() == code)
    }
}

impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.code())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum Branch {
    TheModel,
    TheEnvironment,
    TheArtifact,
    McfItself,
}

impl fmt::Display for Branch {
    fn fmt(&self, form: &mut fmt::Formatter<'_>) -> fmt::Result {
        form.write_str(match self {
            Self::TheModel => "the model under test",
            Self::TheEnvironment => "the environment the run happened in",
            Self::TheArtifact => "the artifact",
            Self::McfItself => "MCF itself",
        })
    }
}
